# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/992/bin/cmake

# The command to remove a file.
RM = /snap/cmake/992/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sullivan/Documents/compsci/cs452/cs-452-lab-02

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sullivan/Documents/compsci/cs452/cs-452-lab-02

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/992/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/992/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sullivan/Documents/compsci/cs452/cs-452-lab-02/CMakeFiles /home/sullivan/Documents/compsci/cs452/cs-452-lab-02//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sullivan/Documents/compsci/cs452/cs-452-lab-02/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cs_452_lab_02

# Build rule for target.
cs_452_lab_02: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cs_452_lab_02
.PHONY : cs_452_lab_02

# fast build rule for target.
cs_452_lab_02/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/build
.PHONY : cs_452_lab_02/fast

Queue.o: Queue.cpp.o
.PHONY : Queue.o

# target to build an object file
Queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/Queue.cpp.o
.PHONY : Queue.cpp.o

Queue.i: Queue.cpp.i
.PHONY : Queue.i

# target to preprocess a source file
Queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/Queue.cpp.i
.PHONY : Queue.cpp.i

Queue.s: Queue.cpp.s
.PHONY : Queue.s

# target to generate assembly for a file
Queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/Queue.cpp.s
.PHONY : Queue.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/main.cpp.s
.PHONY : main.cpp.s

mfqs.o: mfqs.cpp.o
.PHONY : mfqs.o

# target to build an object file
mfqs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/mfqs.cpp.o
.PHONY : mfqs.cpp.o

mfqs.i: mfqs.cpp.i
.PHONY : mfqs.i

# target to preprocess a source file
mfqs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/mfqs.cpp.i
.PHONY : mfqs.cpp.i

mfqs.s: mfqs.cpp.s
.PHONY : mfqs.s

# target to generate assembly for a file
mfqs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/mfqs.cpp.s
.PHONY : mfqs.cpp.s

process.o: process.cpp.o
.PHONY : process.o

# target to build an object file
process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/process.cpp.o
.PHONY : process.cpp.o

process.i: process.cpp.i
.PHONY : process.i

# target to preprocess a source file
process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/process.cpp.i
.PHONY : process.cpp.i

process.s: process.cpp.s
.PHONY : process.s

# target to generate assembly for a file
process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/process.cpp.s
.PHONY : process.cpp.s

rt.o: rt.cpp.o
.PHONY : rt.o

# target to build an object file
rt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/rt.cpp.o
.PHONY : rt.cpp.o

rt.i: rt.cpp.i
.PHONY : rt.i

# target to preprocess a source file
rt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/rt.cpp.i
.PHONY : rt.cpp.i

rt.s: rt.cpp.s
.PHONY : rt.s

# target to generate assembly for a file
rt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs_452_lab_02.dir/build.make CMakeFiles/cs_452_lab_02.dir/rt.cpp.s
.PHONY : rt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cs_452_lab_02"
	@echo "... Queue.o"
	@echo "... Queue.i"
	@echo "... Queue.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mfqs.o"
	@echo "... mfqs.i"
	@echo "... mfqs.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
	@echo "... rt.o"
	@echo "... rt.i"
	@echo "... rt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

